# This file was generated by GoReleaser. DO NOT EDIT.
cask "entire@nightly" do
  version "0.10.1-nightly.202608121908.a47cf0c70"

  on_macos do
    on_intel do
      sha256 "c9c8c327c82efc019f5f22741f04838318c380bb0f0ee2cc88d279e06ae98adc"
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3f3fd6188f7ed91e6452ea32b0b6e86c3854845a886605da24eea651c09d5641"
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "12d553301889fa66cd5a6c35957950afeded5927dd9bb04d1928043cd192ea8f"
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7726efa897de234fa89d24a678998c54b313e5e1b72c42ac419f26e3c8a8dc45"
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_linux_arm64.tar.gz"
    end
  end

  name "entire@nightly"
  desc "CLI for Entire (nightly build)"
  homepage "https://github.com/entireio/cli"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "entire",
    ]

  binary "entire"
  binary "git-remote-entire"

  generate_completions_from_executable "entire",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
