# This file was generated by GoReleaser. DO NOT EDIT.
cask "entire" do
  name "entire"
  desc "CLI for Entire"
  homepage "https://github.com/entireio/cli"
  version "0.4.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "entire"
  bash_completion "completions/entire.bash"
  zsh_completion "completions/entire.zsh"
  fish_completion "completions/entire.fish"

  on_macos do
    on_intel do
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_darwin_amd64.tar.gz"
      sha256 "500f5f6a35669179bc1e57114c78db22df66c461dd1e68e17e3420d815a75b29"
    end
    on_arm do
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_darwin_arm64.tar.gz"
      sha256 "04a4431a5cb3928cb16ca3758e7a278e5325ca8500c35957bf3b240d697a2268"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_linux_amd64.tar.gz"
      sha256 "16723082531d0c7c747761eb1d12567634453a146bfed4966df77b575ec385d8"
    end
    on_arm do
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_linux_arm64.tar.gz"
      sha256 "d2493bde3d6976ef623945fb7e671dcaf6509a29ccb387c0d371bbda82e8facd"
    end
  end

  # No zap stanza required
end
