# This file was generated by GoReleaser. DO NOT EDIT.
cask "entire@nightly" do
  version "0.8.2-nightly.202607080657.93af8254a"

  on_macos do
    on_intel do
      sha256 "671a197294bb5655a3654c89b017f105f10d09899c23b9f2056d69e41d291ed2"
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "91d2b7e598710d491491d88983999a988db761fdfbd1d1051faf5015e21d5370"
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4531f874f6eb0c310cc5449f003423a51a55495f609dfee2531d3c93390de710"
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "07d2e0155fbf8523c5a6f17f84b61e625507deda1c217071e7958abf4c3d155c"
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_linux_arm64.tar.gz"
    end
  end

  name "entire@nightly"
  desc "CLI for Entire (nightly build)"
  homepage "https://github.com/entireio/cli"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "entire",
    ]

  binary "entire"
  binary "git-remote-entire"

  generate_completions_from_executable "entire",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
