# This file was generated by GoReleaser. DO NOT EDIT.
cask "entire" do
  name "entire"
  desc "CLI for Entire"
  homepage "https://github.com/entireio/cli"
  version "0.4.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "entire"
  bash_completion "completions/entire.bash"
  zsh_completion "completions/entire.zsh"
  fish_completion "completions/entire.fish"

  on_macos do
    on_intel do
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_darwin_amd64.tar.gz"
      sha256 "d1bccacaef3149f6481349bd3d9c586242be57fa290176a0b010c9c006ba28b5"
    end
    on_arm do
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_darwin_arm64.tar.gz"
      sha256 "4ddbbda30e1bca1098d8e82e7233b9e6bf06d095060958e52dfdbfedf596b446"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_linux_amd64.tar.gz"
      sha256 "07a404df27ed5872575f1cb2694b0676ded29bf7e6db7ff3c4ff39da80dc53ea"
    end
    on_arm do
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_linux_arm64.tar.gz"
      sha256 "7a3bdc91d3254e8d60b43967c2314d9f80e498f67eeabe05080f5e31c8422e50"
    end
  end

  # No zap stanza required
end
