# This file was generated by GoReleaser. DO NOT EDIT.
cask "entire@nightly" do
  version "0.10.7-nightly.202609080625.78a655db4"

  on_macos do
    on_arm do
      sha256 "bbf841aa3bc39841388fa0821ba8628a854870a13115c13a150702548e3c7ca9"
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7fa982915d87fb539c11ccb4fea001802a97aa8c9f9ae91fec7ad33f76cec0e6"
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2b29a904d7a69697a341714d71d5d138be4715e8e213b1b4c14c80acce7a989f"
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ca59d6325b2b9e3d68300b1da353624ed78c8eca1c2fee9d4674cc41c85603a2"
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_linux_amd64.tar.gz"
    end
  end

  name "entire@nightly"
  desc "CLI for Entire (nightly build)"
  homepage "https://github.com/entireio/cli"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "entire",
    ]

  binary "entire"
  binary "git-remote-entire"

  generate_completions_from_executable "entire",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
