# This file was generated by GoReleaser. DO NOT EDIT.
cask "entire" do
  version "0.7.2"

  on_macos do
    on_intel do
      sha256 "bd5e1f8e66d2dedc674deebf5552a8d0223b89c565454268ec0d708ecb2b1a6e"
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6cb569ab515a2a5c7adef667677f6df6e708566dfe9fc8bbcbe24b7ddbaa7295"
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8dd3c0c50ff355fcf009332448d8e099ebc4d0f83a139e76a44f67b5e2c33764"
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e9986eb96b05a7f708e40f23af1addfa2fc547ab5aebe908df59b3fb293d9c81"
      url "https://github.com/entireio/cli/releases/download/v#{version}/entire_linux_arm64.tar.gz"
    end
  end

  name "entire"
  desc "CLI for Entire"
  homepage "https://github.com/entireio/cli"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "entire@nightly",
    ]

  binary "entire"
  binary "git-remote-entire"

  generate_completions_from_executable "entire",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
