# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-sync" do
  version "0.4.3"

  on_macos do
    on_intel do
      sha256 "a2e09e3400c025c19c4f187cce8f95c72014f9e5deecf53a06b9a2ae4a0e99ee"
      url "https://github.com/entireio/git-sync/releases/download/v#{version}/git-sync_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b75230eb42eab352a135d11a8c193cd9e858dd3e392194a0b546702b466bea49"
      url "https://github.com/entireio/git-sync/releases/download/v#{version}/git-sync_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5b8e09d422dd0d3e1747651ca30854aa28c478304a9d00af87e11987a056cc50"
      url "https://github.com/entireio/git-sync/releases/download/v#{version}/git-sync_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dd100c325e7e6576a277019dfd9883d45f7f07cd967445c549cd462909a735c1"
      url "https://github.com/entireio/git-sync/releases/download/v#{version}/git-sync_#{version}_linux_arm64.tar.gz"
    end
  end

  name "git-sync"
  desc "git-sync — replicate and sync Git repositories"
  homepage "https://github.com/entireio/git-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-sync"

  # No zap stanza required

end
