# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-sync" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "e3e7e3ea7e17f771cbc2cbb8452f8c483d5c95ae7c1d56641e1ac9b829fa23c4"
      url "https://github.com/entireio/git-sync/releases/download/v#{version}/git-sync_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f011c7e7c117ddb4a99e2d7a2a549bc72b754679441bef0ccbe94cf75dfd34bc"
      url "https://github.com/entireio/git-sync/releases/download/v#{version}/git-sync_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "941207602538150d23a2668cbdb16fb93d756f246f41b0c454675b68eef0a1e2"
      url "https://github.com/entireio/git-sync/releases/download/v#{version}/git-sync_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f54e76a0611559507933408f35c83f978d17eee8fc6e2fb6af7a1bb3178c4fe5"
      url "https://github.com/entireio/git-sync/releases/download/v#{version}/git-sync_#{version}_linux_arm64.tar.gz"
    end
  end

  name "git-sync"
  desc "git-sync — replicate and sync Git repositories"
  homepage "https://github.com/entireio/git-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-sync"

  # No zap stanza required

end
