# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-sync" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "5f4a909d07f68e5684264bc761b3602666ab4964cbd8e35dda900d5ddfcab8f9"
      url "https://github.com/entireio/git-sync/releases/download/v#{version}/git-sync_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "313e2a068311f5aba7e571978bac641b651dff806a3266ab7fc896c46ca44368"
      url "https://github.com/entireio/git-sync/releases/download/v#{version}/git-sync_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f72847f48af09214eaec777d52aa72bcd908bef051f42c78045e57d78bd5aa13"
      url "https://github.com/entireio/git-sync/releases/download/v#{version}/git-sync_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3e35cdd57749bc2d1b159d8bcfd59a2f2f0015e66f1b9172ef001420296f9ade"
      url "https://github.com/entireio/git-sync/releases/download/v#{version}/git-sync_#{version}_linux_arm64.tar.gz"
    end
  end

  name "git-sync"
  desc "git-sync — replicate and sync Git repositories"
  homepage "https://github.com/entireio/git-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-sync"

  # No zap stanza required

end
